# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t0q1cDdg-dpcOqnWv7slFKn9kuSauWe8
"""

def calculate_unique_values(t, cases):
    results = []
    for n, coins in cases:
        possible_values = set()
        for coin in coins:
            new_values = set(v + coin for v in possible_values)
            new_values.add(coin)
            possible_values |= new_values
        results.append(len(possible_values))
    return results

# Ejemplo de uso con los datos de la imagen proporcionada
t = 3  # Número de casos
cases = [
    (7, [3, 8, 1, 6, 4, 7, 3, 10]),
    (3, [8, 1, 10]),
    (3, [1, 3, 10])
]

# Calcular los valores únicos
calculate_unique_values(t, cases)